export const SET_POKEMONS = 'SET_POKEMONS';
export const SEARCH_POKEMONS = 'SEARCH_POKEMONS';
export const RESTORE_POKEMON_STATE = 'RESTORE_POKEMON_STATE';

export const ADD_MYPOKEMON = 'ADD_MYPOKEMON';